services:
  - type: web
    name: ayodeji-bot
    env: docker
    plan: free
    region: oregon 
    buildCommand: docker build -t ayodeji .
    startCommand: uvicorn main:app --host 0.0.0.0 --port 80
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ayodeji-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

databases:
  - name: ayodeji-db
    databaseName: ayodeji
    user: ayodeji_user
    plan: free
    region: oregon
